### PR TITLE
fix: remove `lockmarks` from `gc{o,O}`

### LINKED ISSUE #219: Marks are moved by `gcO`
### Incorrect (current) behavior
When running `gcO` on a line that has a mark on it, the mark will be moved to the line the comment is being placed on.

Example:
1. Put this code in a `.cpp` file (to set comment string automatically) and put your cursor on the `f` in `foo`:
```c++
int foo = 5;
```
2. Place mark `m` on the `f` in `foo` (`mm`)
3. Run `gcO` and type " hello". You should now have this:
```c++
// hello
int foo = 5;
```
4. However, mark `m` is also now on the `e` in `hello`. Test this by doing <code>`m</code> to jump to the character the mark is on.

### Expected behavior
The expected behavior is that the mark should remain on the `f` in `foo` that it was placed on to begin with.

### PR DESCRIPTION
**Pull request by PowerUser64**
Resolves #219

### CODE REVIEW

File: lua/Comment/api.lua [hunk 1]
```diff
@@ -478,7 +478,7 @@ api.locked = setmetatable({}, {
         ---@param motion OpMotion
         return function(motion)
             return A.nvim_command(
-                ('lockmarks lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
+                ('lua require("Comment.api").%s(%s)'):format(cb, motion and ('%q'):format(motion))
```
Comment (numToStr) [inline lua/Comment/api.lua:481]: This is clearly not what I wanted, and this will mess up other keybinds. We only need to change the `gc{o,O}` keybinds.

**Review by numToStr — CHANGES_REQUESTED** [review]

File: lua/Comment/api.lua (hunk 1 above)
Comment (PowerUser64) [reply lua/Comment/api.lua:481]: Oh, that was my test to see if it would work. Give me a bit, I'm isolating `gco` and `gcO`.

Comment (bew) [reply lua/Comment/api.lua:481]: I think @numToStr meant to do this diff:
```diff
diff --git a/lua/Comment/api.lua b/lua/Comment/api.lua
index d9b75c9..6c529e3 100644
--- a/lua/Comment/api.lua
+++ b/lua/Comment/api.lua
@@ -555,9 +555,9 @@ function api.setup(config)

         -- Extra Mappings
         if cfg.mappings.extra then
-            K('n', cfg.extra.below, api.locked('insert.linewise.below'), { desc = 'Comment insert below' })
-            K('n', cfg.extra.above, api.locked('insert.linewise.above'), { desc = 'Comment insert above' })
-            K('n', cfg.extra.eol, api.locked('insert.linewise.eol'), { desc = 'Comment insert end of line' })
+            K('n', cfg.extra.below, api.insert.linewise.below, { desc = 'Comment insert below' })
+            K('n', cfg.extra.above, api.insert.linewise.above, { desc = 'Comment insert above' })
+            K('n', cfg.extra.eol, api.insert.linewise.eol, { desc = 'Comment insert end of line' })
         end

         -- Extended Mappings
```

Comment (PowerUser64) [reply lua/Comment/api.lua:481]: Ohh, okay. That's pretty close to something I had tried. Does the last mapping (`gca`) need to be adjusted too? It doesn't change the number of lines, so I don't think it needs to be changed.

Comment (PowerUser64) [reply lua/Comment/api.lua:481]: I tested it, and last one should be left alone or it will clear the marks on the line (it was probably the original reason for adding `lockmarks`)

Comment (bew) [reply lua/Comment/api.lua]: > I tested it, and last one should be left alone or it will clear the marks on the line (it was probably the original reason for adding `lockmarks`)

That's surprising, from my understanding `gcA` should only add to the line, but not touch the rest of the line.. No? 
Or do you use nvim api to replace the line, removing all marks?

Comment (PowerUser64) [reply lua/Comment/api.lua]: It appears the answer is yes. In [lua/Comment/extra.lua#L96](https://github.com/numToStr/Comment.nvim/blob/master/lua/Comment/extra.lua#L96), it the line is reconstructed with the comment at the end, then used to overwrite the current line.

Comment (numToStr) [reply lua/Comment/api.lua]: Yes @PowerUser64 is right, `gcA` shouldn't be changed. The reason behind `lockmarks` is that `nvim_buf_set_lines` and even `nvim_buf_set_text` destroys marks #24.

**Review by numToStr — COMMENTED** [review]
Thanks 👍🏼

**Review by numToStr — APPROVED** [review]
